language: node_js
node_js:
  - "9"
  - "8"
  - "7"
  - "6"

after_success: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
branches:
  only:
    - develop

install:
 - npm install

#before_script:
# - npm run lint
