language: node_js
node_js:
  - "10"
  - "8"

after_success: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
branches:
  only:
    - develop

install:
 - npm install

before_script:
 - npm run lint
